### ISSUE TITLE
use of sed on osx

### ISSUE THREAD

**Issue by avanderpluijm** [oopsmonk/iota_esp32_wallet#1]
Hi, fyi, to make it work on osx, I had to change https://github.com/oopsmonk/iota_cclient_esp32/blob/master/components/iota_cclient/gen_hash_container.sh#L13 
to 
`sed -i.bak "s/{SIZE}/${HASH_SIZE}/g" ${HASH_TEMPLATE_DIR}/${HASH_FILE_NAME}`

**Comment by oopsmonk** [comment]
@avanderpluijm thanks, the problem should be fixed at 4314c16
