### ISSUE TITLE
Error building

### ISSUE THREAD

**Issue by empoweriot** [oopsmonk/iota_esp32_wallet#10]
When I build: idf.py build I receive the following error:

../components/iota_cclient/entangled/utils/containers/hash/hash27_queue.c:10:10: fatal error: utils/containers/hash/hash{SIZE}_queue.h: No such file or directory
 #include "utils/containers/hash/hash{SIZE}_queue.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[38/823] Building C object esp-idf/http_parser/CMakeFiles/__idf_http_parser.dir/http_parser/http_parser.c.obj
ninja: build stopped: subcommand failed.
ninja failed with exit code 1
➜  iota_esp32_wallet git:(master) ✗

How can I solve this?

**Comment by oopsmonk** [comment]
Some source are generated from templates, please run `init.sh` before configuration and compilation. 
https://github.com/oopsmonk/iota_esp32_wallet/blob/master/README.md#step-2-initializing-components

**Comment by oopsmonk** [comment]
@empoweriot do you still have this problem?

**Comment by empoweriot** [comment]
No, I have it working on a Linux machine.

Looks like my set-up on my Mac, maybe $PATH is causing problems.

Darren
