### ISSUE TITLE
E (356) esp32_main: please set a valid seed in sdkconfig!

### ISSUE THREAD

**Issue by empoweriot** [oopsmonk/iota_esp32_wallet#11]
Build works, I verified my seed was correct several times and receive the error:
E (356) esp32_main: please set a valid seed in sdkconfig!

**Comment by empoweriot** [comment]
additional info from build:
[738/759] Building C object esp-idf/iota_cclient/CMakeFiles/__idf_iota_cclient.dir/entangled/cclient/api/extended/send_transfer.c.obj
In file included from ../components/iota_cclient/entangled/cclient/request/add_neighbors.h:21,
                 from ../components/iota_cclient/entangled/cclient/request/requests.h:11,
                 from ../components/iota_cclient/entangled/cclient/serialization/serializer.h:22,
                 from ../components/iota_cclient/entangled/cclient/service.h:22,
                 from ../components/iota_cclient/entangled/cclient/http/http.h:25,
                 from ../components/iota_cclient/entangled/cclient/api/extended/send_transfer.h:20,
                 from ../components/iota_cclient/entangled/cclient/api/extended/send_transfer.c:8:
../components/iota_cclient/entangled/cclient/api/extended/send_transfer.c: In function 'iota_client_send_transfer':
../components/uthash/uthash/src/utarray.h:124:11: warning: comparison of unsigned expression < 0 is always false [-Wtype-limits]
   if ((j) > (a)->i) utarray_resize(a,j);                                      \
           ^
../components/iota_cclient/entangled/cclient/api/extended/send_transfer.c:31:9: note: in expansion of macro 'utarray_insert'
         utarray_insert(raw_tx, serialized_value, 0);
         ^~~~~~~~~~~~~~
../components/uthash/uthash/src/utarray.h:164:23: warning: comparison of unsigned expression < 0 is always false [-Wtype-limits]
   } else if ((dst)->i < (unsigned)(num)) {                                    \
                       ^
../components/uthash/uthash/src/utarray.h:124:21: note: in expansion of macro 'utarray_resize'
   if ((j) > (a)->i) utarray_resize(a,j);                                      \
                     ^~~~~~~~~~~~~~
../components/iota_cclient/entangled/cclient/api/extended/send_transfer.c:31:9: note: in expansion of macro 'utarray_insert'
         utarray_insert(raw_tx, serialized_value, 0);
         ^~~~~~~~~~~~~~
../components/uthash/uthash/src/utarray.h:167:36: warning: comparison of unsigned expression < 0 is always false [-Wtype-limits]
       for (_ut_i = (dst)->i; _ut_i < (unsigned)(num); ++_ut_i) {              \
                                    ^
../components/uthash/uthash/src/utarray.h:124:21: note: in expansion of macro 'utarray_resize'
   if ((j) > (a)->i) utarray_resize(a,j);                                      \
                     ^~~~~~~~~~~~~~
../components/iota_cclient/entangled/cclient/api/extended/send_transfer.c:31:9: note: in expansion of macro 'utarray_insert'
         utarray_insert(raw_tx, serialized_value, 0);
         ^~~~~~~~~~~~~~
[754/759] Building C object esp-idf/main/CMakeFiles/__idf_main.dir/wallet_system.c.obj
In file included from ../main/wallet_system.c:17:
/Users/darrenolson/esp/esp-idf/components/esp32/include/rom/uart.h:1:2: warning: #warning rom/uart.h is deprecated, please use esp32/rom/uart.h instead [-Wcpp]
 #warning rom/uart.h is deprecated, please use esp32/rom/uart.h instead
  ^~~~~~~
../main/wallet_system.c: In function 'fn_send':
../main/wallet_system.c:386:15: warning: unused variable 'tmp_hash' [-Wunused-variable]
   flex_trit_t tmp_hash[FLEX_TRIT_SIZE_243];
               ^~~~~~~~

**Comment by oopsmonk** [comment]
@empoweriot the seed validation checks if it is a string with 81 characters. so please check if the length of the seed is 81 in the sdkconfig file.

**Comment by empoweriot** [comment]
seed was 82
