### ISSUE TITLE
Iota wallet build error

### ISSUE THREAD

**Issue by Maruthamperumal** [oopsmonk/iota_esp32_wallet#14]
Hi Sam,

We are creating iota wallet application with a help form your blog.
During the process, we are facing issue while running "idf.py build" command.
Error screenshot attached for your reference.
please help us how to solve this issue
![Screenshot from 2019-11-15 16-32-35](https://user-images.githubusercontent.com/57746763/68946001-d8824300-07d7-11ea-9aa2-9cc4a88bf11e.png)

**Comment by Maruthamperumal** [comment]
Please refer the additional dependency issue
![Screenshot from 2019-11-15 20-57-47](https://user-images.githubusercontent.com/57746763/68954768-b219d300-07ea-11ea-92fd-c2ec95e8de7a.png)

**Comment by oopsmonk** [comment]
@Maruthamperumal can you update your local repostory and try again? it should be fixed in d96cff3c4e8580d8e2dcd8fc42026a2c76a8abac
