### ISSUE TITLE
Update terminology

### ISSUE THREAD

**Issue by JakeSCahill** [oopsmonk/iota_esp32_wallet#15]
Since we now have Hornet nodes and we will soon have Bee nodes, I think the configuration fields should be renamed to `IOTA node` instead of `IRI node`.

I'm unsure whether this app supports Hornet nodes, which is why I haven't made the change.

If it does, I'm happy to do it 😄

**Comment by oopsmonk** [comment]
sure, there's no reason not to support other node implementation at this moment since iota.c support hornet. the dependencies update is needed before this change.
